#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: Samuel Dezsö Dysch

# Name of the author
author: Sam Dysch

# Short bio or description (displayed in the header)
#description: Postdoctoral research associate, The University of Manchester

# URL of your avatar or profile pic (you could use your GitHub profile pic)
#avatar: /images/me.png

theme: minima

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email: sdysch94+website@gmail.com
  github: sdysch
  gitlab: sdysch
  gitlab_cern: sdysch
  linkedin: sdysch
  twitter: sam_dysch


# Your website URL
url: https://sdysch.github.io/
enforce_ssl: sdysch.github.io/

baseurl: ''

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
plugins:
  - jekyll-seo-tag

include: ['_pages']

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

